language: c
services: PostgreSQL
env:
  - global:
    - WARNINGS_ARE_ERRORS=1
    - R_BUILD_ARGS=--no-manual
    - R_CHECK_ARGS=--no-manual --as-cran

before_install:
  - curl -OL http://raw.github.com/craigcitro/r-travis/master/scripts/travis-tool.sh
  - chmod 755 ./travis-tool.sh
  - ./travis-tool.sh bootstrap
install:
  - ./travis-tool.sh r_binary_install ggplot2
  - ./travis-tool.sh r_binary_install RSQLite
  - ./travis-tool.sh r_binary_install RMySQL
  - ./travis-tool.sh r_binary_install rgl
  - ./travis-tool.sh r_binary_install XML
  - ./travis-tool.sh github_package assertthat
  - ./travis-tool.sh github_package testthat
  - ./travis-tool.sh github_package bigrquery
  - ./travis-tool.sh install_deps

before_script:
- psql -c 'create database lahman;' -U postgres
- psql -c 'create database hflights;' -U postgres
script: ./travis-tool.sh run_tests

on_failure:
  - ./travis-tool.sh dump_logs

branches:
  except:
  - /-expt$/
notifications:
  email:
    on_success: change
    on_failure: change

