# DO NOT CHANGE the "init" and "install" sections below

# Download script file from GitHub
init:
  ps: |
        $ErrorActionPreference = "Stop"
        Invoke-WebRequest http://raw.github.com/krlmlr/r-appveyor/master/scripts/appveyor-tool.ps1 -OutFile "..\appveyor-tool.ps1"
        Import-Module '..\appveyor-tool.ps1'

install:
  - ps: Bootstrap
  - cmd: Rscript -e "writeLines('options(repos = \'https://cloud.r-project.org\')', '~/.Rprofile')"
  - cmd: Rscript -e "getOption('repos')"
  - cmd: mkdir "C:\tic-library"
  - cmd: Rscript -e "install.packages('remotes'); .libPaths(c('C:/tic-library', .libPaths())); remotes::install_github('ropenscilabs/tic@f-callr')"
  - cmd: Rscript -e "library(tic, lib.loc = 'C:/tic-library'); prepare_all_stages()"

before_build: Rscript -e "library(tic, lib.loc = 'C:/tic-library'); before_install()"
build_script: Rscript -e "library(tic, lib.loc = 'C:/tic-library'); install()"
after_build: Rscript -e "library(tic, lib.loc = 'C:/tic-library'); after_install()"
before_test: Rscript -e "library(tic, lib.loc = 'C:/tic-library'); before_script()"
test_script: Rscript -e "library(tic, lib.loc = 'C:/tic-library'); script()"
on_success: Rscript -e "try(library(tic, lib.loc = 'C:/tic-library'); after_success(), silent = TRUE)"
on_failure: Rscript -e "library(tic, lib.loc = 'C:/tic-library'); after_failure()"
before_deploy: Rscript -e "library(tic, lib.loc = 'C:/tic-library'); before_deploy()"
deploy_script: Rscript -e "library(tic, lib.loc = 'C:/tic-library'); deploy()"
after_deploy: Rscript -e "library(tic, lib.loc = 'C:/tic-library'); after_deploy()"
on_finish: Rscript -e "library(tic, lib.loc = 'C:/tic-library'); after_script()"

# Adapt as necessary starting from here

#on_failure:
#  - 7z a failure.zip *.Rcheck\*
#  - appveyor PushArtifact failure.zip

environment:
  R_REMOTES_STANDALONE: true
  GITHUB_PAT:
    secure: ydE+Zo04e/ffDUNpRKEqjTJFbiL/aozpxl886+6s8YSPtUDOcUbhNmwmhYlY10sc

artifacts:
  - path: '*.Rcheck\**\*.log'
    name: Logs

  - path: '*.Rcheck\**\*.out'
    name: Logs

  - path: '*.Rcheck\**\*.fail'
    name: Logs

  - path: '*.Rcheck\**\*.Rout'
    name: Logs

  - path: '\*_*.tar.gz'
    name: Bits

  - path: '\*_*.zip'
    name: Bits
